// Generated by Haxe 3.4.0

#pragma warning disable 109, 114, 219, 429, 168, 162
public class Reflect : global::haxe.lang.HxObject {
	
	public Reflect(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public Reflect() {
		#line 33 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
		global::Reflect.__hx_ctor__Reflect(this);
	}
	#line default
	
	public static void __hx_ctor__Reflect(global::Reflect __hx_this) {
	}
	
	
	public static object field(object o, string field) {
		#line 46 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
		global::haxe.lang.IHxObject ihx = ((global::haxe.lang.IHxObject) (( o as global::haxe.lang.IHxObject )) );
		if (( ihx != null )) {
			#line 47 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
			return ihx.__hx_getField(field, global::haxe.lang.FieldLookup.hash(field), false, false, false);
		}
		
		#line 49 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
		return global::haxe.lang.Runtime.slowGetField(o, field, false);
	}
	#line default
	
	public static void setField(object o, string field, object @value) {
		#line 55 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
		global::haxe.lang.IHxObject ihx = ((global::haxe.lang.IHxObject) (( o as global::haxe.lang.IHxObject )) );
		if (( ihx != null )) {
			#line 57 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
			ihx.__hx_setField(field, global::haxe.lang.FieldLookup.hash(field), @value, false);
		}
		else {
			#line 59 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
			global::haxe.lang.Runtime.slowSetField(o, field, @value);
		}
		
	}
	#line default
	
	public static global::Array<object> fields(object o) {
		#line 92 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
		global::haxe.lang.IHxObject ihx = ((global::haxe.lang.IHxObject) (( o as global::haxe.lang.IHxObject )) );
		if (( ihx != null )) {
			#line 95 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
			global::Array<object> ret = new global::Array<object>(new object[]{});
			ihx.__hx_getFields(ret);
			#line 97 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
			return ret;
		}
		else if (( o is global::System.Type )) {
			#line 99 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
			return global::Type.getClassFields(((global::System.Type) (o) ));
		}
		else {
			#line 101 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
			return global::Reflect.instanceFields(o.GetType());
		}
		
	}
	#line default
	
	public static global::Array<object> instanceFields(global::System.Type c) {
		#line 108 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
		global::Array<object> ret = new global::Array<object>(new object[]{});
		global::System.Reflection.FieldInfo[] mis = ((global::System.Type) (c) ).GetFields(((global::System.Reflection.BindingFlags) (( ((global::System.Reflection.BindingFlags) (( ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Public) ) | ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Instance) ) )) ) | ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.FlattenHierarchy) ) )) ));
		#line 110 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
		{
			#line 110 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
			int _g1 = 0;
			#line 110 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
			int _g = ( mis as global::System.Array ).Length;
			#line 110 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
			while (( _g1 < _g )) {
				#line 113 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
				ret.push(( mis[_g1++] as global::System.Reflection.MemberInfo ).Name);
			}
			
		}
		
		#line 115 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Reflect.hx"
		return ret;
	}
	#line default
	
}


