// Generated by Haxe 3.4.0

#pragma warning disable 109, 114, 219, 429, 168, 162
public class Type : global::haxe.lang.HxObject {
	
	public Type(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public Type() {
		#line 43 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
		global::Type.__hx_ctor__Type(this);
	}
	#line default
	
	public static void __hx_ctor__Type(global::Type __hx_this) {
	}
	
	
	public static global::System.Type getClass<T>(T o) {
		#line 47 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
		if (( ( global::System.Object.ReferenceEquals(((object) (o) ), default(object)) || ( o is global::haxe.lang.DynamicObject ) ) || ( o is global::System.Type ) )) {
			#line 48 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
			return null;
		}
		
		#line 50 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
		return o.GetType();
	}
	#line default
	
	public static global::Array<object> getClassFields(global::System.Type c) {
		#line 240 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
		if (global::System.Object.ReferenceEquals(((object) (c) ), ((object) (typeof(string)) ))) {
			#line 242 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
			return new global::Array<object>(new object[]{"fromCharCode"});
		}
		
		#line 245 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
		global::Array<object> ret = new global::Array<object>(new object[]{});
		global::System.Reflection.MemberInfo[] infos = ((global::System.Type) (c) ).GetMembers(((global::System.Reflection.BindingFlags) (( ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Public) ) | ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Static) ) )) ));
		#line 247 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
		{
			#line 247 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
			int _g1 = 0;
			#line 247 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
			int _g = ( infos as global::System.Array ).Length;
			#line 247 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
			while (( _g1 < _g )) {
				#line 249 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
				string name = infos[_g1++].Name;
				if ( ! (name.StartsWith("__hx_")) ) {
					#line 252 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
					ret.push(name);
				}
				
			}
			
		}
		
		#line 255 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
		return ret;
	}
	#line default
	
	public static bool enumEq<T>(T a, T b) {
		#line 314 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
		if (global::haxe.lang.Runtime.eq(a, default(T))) {
			#line 315 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
			return global::haxe.lang.Runtime.eq(b, default(T));
		}
		else if (global::haxe.lang.Runtime.eq(b, default(T))) {
			#line 317 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
			return false;
		}
		else {
			#line 319 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
			return a.Equals(b);
		}
		
	}
	#line default
	
	public static int enumIndex(object e) {
		#line 335 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
		if (( e is global::System.Enum )) {
			#line 337 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
			global::System.Array values = global::System.Enum.GetValues(((global::System.Type) (e.GetType()) ));
			return global::System.Array.IndexOf(((global::System.Array) (values) ), ((object) (e) ));
		}
		else {
			#line 340 "C:\\HaxeToolkit\\haxe\\std\\cs\\_std\\Type.hx"
			return (((global::haxe.lang.Enum) (e) )).index;
		}
		
	}
	#line default
	
}


