// Generated by Haxe 3.4.0

namespace haxe.lang{
	public enum EmptyObject{
		EMPTY
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.lang {
	public class Runtime {
		
		
	public static object getField(haxe.lang.HxObject obj, string field, int fieldHash, bool throwErrors)
	{
		if (obj == null && !throwErrors) return null;
		return obj.__hx_getField(field, (fieldHash == 0) ? haxe.lang.FieldLookup.hash(field) : fieldHash, throwErrors, false, false);
	}

	public static double getField_f(haxe.lang.HxObject obj, string field, int fieldHash, bool throwErrors)
	{
		if (obj == null && !throwErrors) return 0.0;
		return obj.__hx_getField_f(field, (fieldHash == 0) ? haxe.lang.FieldLookup.hash(field) : fieldHash, throwErrors, false);
	}

	public static object setField(haxe.lang.HxObject obj, string field, int fieldHash, object value)
	{
		return obj.__hx_setField(field, (fieldHash == 0) ? haxe.lang.FieldLookup.hash(field) : fieldHash, value, false);
	}

	public static double setField_f(haxe.lang.HxObject obj, string field, int fieldHash, double value)
	{
		return obj.__hx_setField_f(field, (fieldHash == 0) ? haxe.lang.FieldLookup.hash(field) : fieldHash, value, false);
	}

	public static object callField(haxe.lang.HxObject obj, string field, int fieldHash, Array args)
	{
		return obj.__hx_invokeField(field, (fieldHash == 0) ? haxe.lang.FieldLookup.hash(field) : fieldHash, args);
	}
		public Runtime() {
		}
		
		
		public static readonly object undefined = ((object) (new global::System.Object()) );
		
		public static object closure(object obj, int hash, string field) {
			#line 78 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			return new global::haxe.lang.Closure(obj, field, hash);
		}
		#line default
		
		public static bool eq(object v1, object v2) {
			#line 83 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (global::System.Object.ReferenceEquals(((object) (v1) ), ((object) (v2) ))) {
				#line 84 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return true;
			}
			
			#line 85 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( global::System.Object.ReferenceEquals(((object) (v1) ), default(object)) || global::System.Object.ReferenceEquals(((object) (v2) ), default(object)) )) {
				#line 86 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return false;
			}
			
			#line 88 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::System.IConvertible v1c = ((global::System.IConvertible) (( v1 as global::System.IConvertible )) );
			if (( v1c != null )) {
				#line 91 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				global::System.IConvertible v2c = ((global::System.IConvertible) (( v2 as global::System.IConvertible )) );
				if (( v2c == null )) {
					#line 94 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return false;
				}
				
				#line 97 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				global::System.TypeCode t1 = v1c.GetTypeCode();
				#line 97 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				global::System.TypeCode t2 = v2c.GetTypeCode();
				#line 99 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (( t1 == t2 )) {
					#line 100 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return global::System.Object.Equals(((object) (v1c) ), ((object) (v2c) ));
				}
				
				#line 102 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (( ( t1 == global::System.TypeCode.String ) || ( t2 == global::System.TypeCode.String ) )) {
					#line 103 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return false;
				}
				
				#line 105 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				switch (t1) {
					case global::System.TypeCode.Int64:
					{
						#line 105 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						switch (t2) {
							case global::System.TypeCode.Int64:
							case global::System.TypeCode.UInt64:
							case global::System.TypeCode.Single:
							case global::System.TypeCode.Double:
							case global::System.TypeCode.DateTime:
							{
								#line 110 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return ( ((long) (v1c.ToInt64(default(global::System.IFormatProvider))) ) == ((long) (v2c.ToInt64(default(global::System.IFormatProvider))) ) );
							}
							
							
							case global::System.TypeCode.Decimal:
							{
								#line 108 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return v1c.ToDecimal(default(global::System.IFormatProvider)).Equals(v2c.ToDecimal(default(global::System.IFormatProvider)));
							}
							
							
							default:
							{
								#line 110 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return ( ((long) (v1c.ToInt64(default(global::System.IFormatProvider))) ) == ((long) (v2c.ToInt64(default(global::System.IFormatProvider))) ) );
							}
							
						}
						
					}
					
					
					case global::System.TypeCode.UInt64:
					case global::System.TypeCode.DateTime:
					{
						#line 105 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						switch (t2) {
							case global::System.TypeCode.Int64:
							{
								#line 110 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return ( ((long) (v1c.ToInt64(default(global::System.IFormatProvider))) ) == ((long) (v2c.ToInt64(default(global::System.IFormatProvider))) ) );
							}
							
							
							case global::System.TypeCode.UInt64:
							case global::System.TypeCode.Single:
							case global::System.TypeCode.Double:
							case global::System.TypeCode.DateTime:
							{
								#line 112 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return ( v1c.ToUInt64(default(global::System.IFormatProvider)) == v2c.ToUInt64(default(global::System.IFormatProvider)) );
							}
							
							
							case global::System.TypeCode.Decimal:
							{
								#line 108 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return v1c.ToDecimal(default(global::System.IFormatProvider)).Equals(v2c.ToDecimal(default(global::System.IFormatProvider)));
							}
							
							
							default:
							{
								#line 112 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return ( v1c.ToUInt64(default(global::System.IFormatProvider)) == v2c.ToUInt64(default(global::System.IFormatProvider)) );
							}
							
						}
						
					}
					
					
					case global::System.TypeCode.Single:
					case global::System.TypeCode.Double:
					{
						#line 105 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						switch (t2) {
							case global::System.TypeCode.Int64:
							{
								#line 110 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return ( ((long) (v1c.ToInt64(default(global::System.IFormatProvider))) ) == ((long) (v2c.ToInt64(default(global::System.IFormatProvider))) ) );
							}
							
							
							case global::System.TypeCode.UInt64:
							case global::System.TypeCode.DateTime:
							{
								#line 112 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return ( v1c.ToUInt64(default(global::System.IFormatProvider)) == v2c.ToUInt64(default(global::System.IFormatProvider)) );
							}
							
							
							case global::System.TypeCode.Single:
							case global::System.TypeCode.Double:
							{
								#line 114 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return ( v1c.ToDouble(default(global::System.IFormatProvider)) == v2c.ToDouble(default(global::System.IFormatProvider)) );
							}
							
							
							case global::System.TypeCode.Decimal:
							{
								#line 108 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return v1c.ToDecimal(default(global::System.IFormatProvider)).Equals(v2c.ToDecimal(default(global::System.IFormatProvider)));
							}
							
							
							default:
							{
								#line 114 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return ( v1c.ToDouble(default(global::System.IFormatProvider)) == v2c.ToDouble(default(global::System.IFormatProvider)) );
							}
							
						}
						
					}
					
					
					case global::System.TypeCode.Decimal:
					{
						#line 108 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						return v1c.ToDecimal(default(global::System.IFormatProvider)).Equals(v2c.ToDecimal(default(global::System.IFormatProvider)));
					}
					
					
					default:
					{
						#line 105 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						switch (t2) {
							case global::System.TypeCode.Int64:
							{
								#line 110 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return ( ((long) (v1c.ToInt64(default(global::System.IFormatProvider))) ) == ((long) (v2c.ToInt64(default(global::System.IFormatProvider))) ) );
							}
							
							
							case global::System.TypeCode.UInt64:
							case global::System.TypeCode.DateTime:
							{
								#line 112 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return ( v1c.ToUInt64(default(global::System.IFormatProvider)) == v2c.ToUInt64(default(global::System.IFormatProvider)) );
							}
							
							
							case global::System.TypeCode.Single:
							case global::System.TypeCode.Double:
							{
								#line 114 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return ( v1c.ToDouble(default(global::System.IFormatProvider)) == v2c.ToDouble(default(global::System.IFormatProvider)) );
							}
							
							
							case global::System.TypeCode.Decimal:
							{
								#line 108 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return v1c.ToDecimal(default(global::System.IFormatProvider)).Equals(v2c.ToDecimal(default(global::System.IFormatProvider)));
							}
							
							
							default:
							{
								#line 116 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return ( v1c.ToInt32(default(global::System.IFormatProvider)) == v2c.ToInt32(default(global::System.IFormatProvider)) );
							}
							
						}
						
					}
					
				}
				
			}
			
			#line 121 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( ((global::System.ValueType) (( v1 as global::System.ValueType )) ) != null )) {
				#line 123 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return v1.Equals(v2);
			}
			else {
				#line 126 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				global::System.Type v1t = ((global::System.Type) (( v1 as global::System.Type )) );
				if (( v1t != null )) {
					#line 129 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					global::System.Type v2t = ((global::System.Type) (( v2 as global::System.Type )) );
					if (( v2t != null )) {
						#line 131 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						return global::haxe.lang.Runtime.typeEq(v1t, v2t);
					}
					
					#line 132 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return false;
				}
				
			}
			
			#line 137 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			return false;
		}
		#line default
		
		public static bool refEq(object v1, object v2) {
			#line 143 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( v1 is global::System.Type )) {
				#line 144 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return global::haxe.lang.Runtime.typeEq(((global::System.Type) (( v1 as global::System.Type )) ), ((global::System.Type) (( v2 as global::System.Type )) ));
			}
			
			#line 146 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			return global::System.Object.ReferenceEquals(((object) (v1) ), ((object) (v2) ));
		}
		#line default
		
		public static double toDouble(object obj) {
			#line 151 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( obj == null )) {
				#line 151 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return .0;
			}
			else if (( obj is double )) {
				#line 151 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return ((double) (obj) );
			}
			else {
				#line 151 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return ((global::System.IConvertible) (( obj as global::System.IConvertible )) ).ToDouble(default(global::System.IFormatProvider));
			}
			
		}
		#line default
		
		public static int toInt(object obj) {
			#line 156 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( obj == null )) {
				#line 156 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return 0;
			}
			else if (( obj is int )) {
				#line 156 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return ((int) (obj) );
			}
			else {
				#line 156 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return ((global::System.IConvertible) (( obj as global::System.IConvertible )) ).ToInt32(default(global::System.IFormatProvider));
			}
			
		}
		#line default
		
		public static bool isInt(object obj) {
			#line 168 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::System.IConvertible cv1 = ((global::System.IConvertible) (( obj as global::System.IConvertible )) );
			if (( cv1 != null )) {
				#line 171 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				switch (cv1.GetTypeCode()) {
					case global::System.TypeCode.Int32:
					case global::System.TypeCode.UInt32:
					{
						#line 177 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						return true;
					}
					
					
					case global::System.TypeCode.Double:
					{
						#line 174 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						double d = ((double) (obj) );
						if (( ( d >= global::System.Int32.MinValue ) && ( d <= global::System.Int32.MaxValue ) )) {
							#line 175 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							return ( d == ((int) (d) ) );
						}
						else {
							#line 175 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							return false;
						}
						
					}
					
					
					default:
					{
						#line 179 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						return false;
					}
					
				}
				
			}
			
			#line 182 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			return false;
		}
		#line default
		
		public static bool isUInt(object obj) {
			#line 187 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::System.IConvertible cv1 = ((global::System.IConvertible) (( obj as global::System.IConvertible )) );
			if (( cv1 != null )) {
				#line 190 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				switch (cv1.GetTypeCode()) {
					case global::System.TypeCode.UInt32:
					{
						#line 196 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						return true;
					}
					
					
					case global::System.TypeCode.Double:
					{
						#line 193 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						double d = ((double) (obj) );
						if (( ((bool) (( d >= global::System.UInt32.MinValue )) ) && ((bool) (( d <= global::System.UInt32.MaxValue )) ) )) {
							#line 194 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							return ((bool) (( ((uint) (d) ) == d )) );
						}
						else {
							#line 194 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							return false;
						}
						
					}
					
					
					default:
					{
						#line 198 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						return false;
					}
					
				}
				
			}
			
			#line 202 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			return false;
		}
		#line default
		
		public static int compare(object v1, object v2) {
			unchecked {
				#line 207 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (global::System.Object.ReferenceEquals(((object) (v1) ), ((object) (v2) ))) {
					#line 207 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return 0;
				}
				
				#line 208 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (global::System.Object.ReferenceEquals(((object) (v1) ), default(object))) {
					#line 208 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return -1;
				}
				
				#line 209 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (global::System.Object.ReferenceEquals(((object) (v2) ), default(object))) {
					#line 209 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return 1;
				}
				
				#line 211 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				global::System.IConvertible cv1 = ((global::System.IConvertible) (( v1 as global::System.IConvertible )) );
				if (( cv1 != null )) {
					#line 214 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					global::System.IConvertible cv2 = ((global::System.IConvertible) (( v2 as global::System.IConvertible )) );
					#line 216 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					if (( cv2 == null )) {
						#line 218 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						throw new global::System.ArgumentException(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Cannot compare ", ( v1.GetType() as global::System.Reflection.MemberInfo ).ToString()), " and "), ( v2.GetType() as global::System.Reflection.MemberInfo ).ToString()));
					}
					
					#line 221 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					switch (cv1.GetTypeCode()) {
						case global::System.TypeCode.Double:
						{
							#line 230 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							double d1 = ((double) (v1) );
							#line 230 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							double d2 = cv2.ToDouble(default(global::System.IFormatProvider));
							#line 232 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							if (( d1 < d2 )) {
								#line 232 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return -1;
							}
							else if (( d1 > d2 )) {
								#line 232 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return 1;
							}
							else {
								#line 232 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return 0;
							}
							
						}
						
						
						case global::System.TypeCode.String:
						{
							#line 224 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							if (( cv2.GetTypeCode() != global::System.TypeCode.String )) {
								#line 225 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								throw new global::System.ArgumentException(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Cannot compare ", ( v1.GetType() as global::System.Reflection.MemberInfo ).ToString()), " and "), ( v2.GetType() as global::System.Reflection.MemberInfo ).ToString()));
							}
							
							#line 228 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							return string.Compare(((string) (( v1 as string )) ), ((string) (( v2 as string )) ), ((global::System.StringComparison) (global::System.StringComparison.Ordinal) ));
						}
						
						
						default:
						{
							#line 234 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							double d1d = cv1.ToDouble(default(global::System.IFormatProvider));
							double d2d = cv2.ToDouble(default(global::System.IFormatProvider));
							#line 236 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							if (( d1d < d2d )) {
								#line 236 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return -1;
							}
							else if (( d1d > d2d )) {
								#line 236 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return 1;
							}
							else {
								#line 236 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return 0;
							}
							
						}
						
					}
					
				}
				
				#line 240 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				global::System.IComparable c1 = ((global::System.IComparable) (( v1 as global::System.IComparable )) );
				global::System.IComparable c2 = ((global::System.IComparable) (( v2 as global::System.IComparable )) );
				#line 243 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (( ( c1 == null ) || ( c2 == null ) )) {
					#line 245 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					throw new global::System.ArgumentException(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Cannot compare ", ( v1.GetType() as global::System.Reflection.MemberInfo ).ToString()), " and "), ( v2.GetType() as global::System.Reflection.MemberInfo ).ToString()));
				}
				
				#line 248 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return c1.CompareTo(((object) (c2) ));
			}
			#line default
		}
		
		
		public static object plus(object v1, object v2) {
			#line 253 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( ( v1 is string ) || ( v2 is string ) )) {
				#line 254 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return global::haxe.lang.Runtime.concat(global::Std.@string(v1), global::Std.@string(v2));
			}
			
			#line 256 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( v1 == null )) {
				#line 258 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (( v2 == null )) {
					#line 258 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return null;
				}
				
				#line 259 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				v1 = 0;
			}
			else if (( v2 == null )) {
				#line 260 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				v2 = 0;
			}
			
			#line 262 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::System.IConvertible cv1 = ((global::System.IConvertible) (( v1 as global::System.IConvertible )) );
			if (( cv1 != null )) {
				#line 265 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				global::System.IConvertible cv2 = ((global::System.IConvertible) (( v2 as global::System.IConvertible )) );
				if (( cv2 == null )) {
					#line 268 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					throw new global::System.ArgumentException(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Cannot dynamically add ", ( v1.GetType() as global::System.Reflection.MemberInfo ).ToString()), " and "), ( v2.GetType() as global::System.Reflection.MemberInfo ).ToString()));
				}
				
				#line 270 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return ( cv1.ToDouble(default(global::System.IFormatProvider)) + cv2.ToDouble(default(global::System.IFormatProvider)) );
			}
			
			#line 273 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			throw new global::System.ArgumentException(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Cannot dynamically add ", global::Std.@string(v1)), " and "), global::Std.@string(v2)));
		}
		#line default
		
		public static object slowGetField(object obj, string field, bool throwErrors) {
			#line 278 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( obj == null )) {
				#line 279 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (throwErrors) {
					#line 280 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					throw new global::System.NullReferenceException(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Cannot access field \'", field), "\' of null."));
				}
				else {
					#line 282 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return null;
				}
				
			}
			
			#line 284 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::System.Type t = ((global::System.Type) (( obj as global::System.Type )) );
			global::System.Reflection.BindingFlags bf = default(global::System.Reflection.BindingFlags);
			#line 286 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( t == null )) {
				#line 288 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				string s = ((string) (( obj as string )) );
				if ( ! (string.Equals(s, null)) ) {
					#line 290 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return global::haxe.lang.StringRefl.handleGetField(s, field, throwErrors);
				}
				
				#line 291 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				t = ((global::System.Type) (obj.GetType()) );
				#line 285 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				bf = ((global::System.Reflection.BindingFlags) (( ((global::System.Reflection.BindingFlags) (( ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Instance) ) | ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Public) ) )) ) | ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.FlattenHierarchy) ) )) );
			}
			else {
				#line 294 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (( ( t == ((global::System.Type) (typeof(string)) ) ) && string.Equals(field, "fromCharCode") )) {
					#line 295 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return new global::haxe.lang.Closure(typeof(global::haxe.lang.StringExt), field, 0);
				}
				
				#line 297 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				obj = null;
				#line 285 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				bf = ((global::System.Reflection.BindingFlags) (( ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Static) ) | ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Public) ) )) );
			}
			
			#line 301 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::System.Reflection.FieldInfo f = t.GetField(((string) (field) ), ((global::System.Reflection.BindingFlags) (bf) ));
			if (( f != null )) {
				#line 304 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return global::haxe.lang.Runtime.unbox(f.GetValue(((object) (obj) )));
			}
			else {
				#line 308 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				global::System.Reflection.PropertyInfo prop = t.GetProperty(((string) (field) ), ((global::System.Reflection.BindingFlags) (bf) ));
				if (( prop == null )) {
					#line 311 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					global::System.Reflection.MemberInfo[] m = t.GetMember(((string) (field) ), ((global::System.Reflection.BindingFlags) (bf) ));
					if (( ( ( m as global::System.Array ).Length == 0 ) && (( string.Equals(field, "__get") || string.Equals(field, "__set") )) )) {
						#line 313 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						m = t.GetMember(((string) (( (string.Equals(field, "__get")) ? ("get_Item") : ("set_Item") )) ), ((global::System.Reflection.BindingFlags) (bf) ));
					}
					
					#line 315 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					if (( ( m as global::System.Array ).Length > 0 )) {
						#line 317 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						return new global::haxe.lang.Closure(( (( obj != null )) ? (obj) : ((object) (t) ) ), field, 0);
					}
					else {
						#line 322 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						if (t.IsCOMObject) {
							#line 326 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							try {
								#line 326 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								return t.InvokeMember(((string) (field) ), ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.GetProperty) ), default(global::System.Reflection.Binder), ((object) (obj) ), ((object[]) (new object[0]) ));
							}
							catch (global::System.Exception e){
								#line 329 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								global::haxe.lang.Exceptions.exception = e;
							}
							
							
						}
						
						#line 334 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						if (throwErrors) {
							#line 335 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							throw global::haxe.lang.HaxeException.wrap(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Cannot access field \'", field), "\'."));
						}
						else {
							#line 337 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							return null;
						}
						
					}
					
				}
				
				#line 340 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return global::haxe.lang.Runtime.unbox(prop.GetValue(((object) (obj) ), default(object[])));
			}
			
		}
		#line default
		
		public static bool slowHasField(object obj, string field) {
			#line 346 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( obj == null )) {
				#line 346 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return false;
			}
			
			#line 347 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::System.Type t = ((global::System.Type) (( obj as global::System.Type )) );
			global::System.Reflection.BindingFlags bf = default(global::System.Reflection.BindingFlags);
			#line 349 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( t == null )) {
				#line 350 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				string s = ((string) (( obj as string )) );
				if ( ! (string.Equals(s, null)) ) {
					#line 352 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return ( global::haxe.lang.StringRefl.handleGetField(s, field, false) != null );
				}
				
				#line 353 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				t = ((global::System.Type) (obj.GetType()) );
				#line 348 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				bf = ((global::System.Reflection.BindingFlags) (( ((global::System.Reflection.BindingFlags) (( ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Instance) ) | ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Public) ) )) ) | ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.FlattenHierarchy) ) )) );
			}
			else {
				#line 356 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (( t == ((global::System.Type) (typeof(string)) ) )) {
					#line 357 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return string.Equals(field, "fromCharCode");
				}
				
				#line 358 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				obj = null;
				#line 348 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				bf = ((global::System.Reflection.BindingFlags) (( ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Static) ) | ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Public) ) )) );
			}
			
			#line 361 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::System.Reflection.MemberInfo[] mi = t.GetMember(((string) (field) ), ((global::System.Reflection.BindingFlags) (bf) ));
			if (( mi != null )) {
				#line 362 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return ( ( mi as global::System.Array ).Length > 0 );
			}
			else {
				#line 362 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return false;
			}
			
		}
		#line default
		
		public static object slowSetField(object obj, string field, object @value) {
			#line 367 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( obj == null )) {
				#line 368 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				throw new global::System.NullReferenceException(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Cannot access field \'", field), "\' of null."));
			}
			
			#line 370 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::System.Type t = ((global::System.Type) (( obj as global::System.Type )) );
			global::System.Reflection.BindingFlags bf = default(global::System.Reflection.BindingFlags);
			#line 372 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( t == null )) {
				#line 374 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				t = ((global::System.Type) (obj.GetType()) );
				#line 371 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				bf = ((global::System.Reflection.BindingFlags) (( ((global::System.Reflection.BindingFlags) (( ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Instance) ) | ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Public) ) )) ) | ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.FlattenHierarchy) ) )) );
			}
			else {
				#line 377 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				obj = null;
				#line 371 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				bf = ((global::System.Reflection.BindingFlags) (( ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Static) ) | ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Public) ) )) );
			}
			
			#line 381 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::System.Reflection.FieldInfo f = t.GetField(((string) (field) ), ((global::System.Reflection.BindingFlags) (bf) ));
			if (( f != null )) {
				#line 384 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (( f.FieldType as global::System.Reflection.MemberInfo ).ToString().StartsWith("haxe.lang.Null")) {
					#line 386 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					@value = global::haxe.lang.Runtime.mkNullable(@value, f.FieldType);
				}
				
				#line 388 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (( ( ( @value != null ) && global::System.Object.ReferenceEquals(((global::System.Type) (typeof(global::System.Double)) ), ((object) (@value.GetType()) )) ) &&  ! (global::System.Object.ReferenceEquals(((object) (t) ), ((object) (f.FieldType) )))  )) {
					#line 391 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					@value = ((global::System.IConvertible) (( @value as global::System.IConvertible )) ).ToType(((global::System.Type) (f.FieldType) ), default(global::System.IFormatProvider));
				}
				
				#line 394 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				f.SetValue(((object) (obj) ), ((object) (@value) ));
				return @value;
			}
			else {
				#line 399 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				global::System.Reflection.PropertyInfo prop = t.GetProperty(((string) (field) ), ((global::System.Reflection.BindingFlags) (bf) ));
				if (( prop == null )) {
					#line 403 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					if (t.IsCOMObject) {
						#line 407 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						try {
							#line 407 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							return t.InvokeMember(((string) (field) ), ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.SetProperty) ), default(global::System.Reflection.Binder), ((object) (obj) ), ((object[]) (new object[]{((object) (@value) )}) ));
						}
						catch (global::System.Exception e){
							#line 410 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							global::haxe.lang.Exceptions.exception = e;
						}
						
						
					}
					
					#line 414 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					throw global::haxe.lang.HaxeException.wrap(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Field \'", field), "\' not found for writing from Class "), global::Std.@string(t)));
				}
				
				#line 417 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (( prop.PropertyType as global::System.Reflection.MemberInfo ).ToString().StartsWith("haxe.lang.Null")) {
					#line 419 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					@value = global::haxe.lang.Runtime.mkNullable(@value, prop.PropertyType);
				}
				
				#line 421 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (( global::System.Object.ReferenceEquals(((global::System.Type) (typeof(global::System.Double)) ), ((object) (@value.GetType()) )) &&  ! (global::System.Object.ReferenceEquals(((object) (t) ), ((object) (f.FieldType) )))  )) {
					#line 424 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					@value = ((global::System.IConvertible) (( @value as global::System.IConvertible )) ).ToType(((global::System.Type) (f.FieldType) ), default(global::System.IFormatProvider));
				}
				
				#line 426 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				prop.SetValue(((object) (obj) ), ((object) (@value) ), default(object[]));
				#line 428 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return @value;
			}
			
		}
		#line default
		
		public static object callMethod(object obj, global::System.Reflection.MethodBase[] methods, int methodLength, global::Array args) {
			unchecked {
				#line 434 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (( methodLength == 0 )) {
					#line 434 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					throw global::haxe.lang.HaxeException.wrap("No available methods");
				}
				
				#line 435 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				int length = ((int) (global::haxe.lang.Runtime.getField_f(args, "length", 520590566, true)) );
				object[] oargs = new object[length];
				#line 437 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				global::System.Type[] ts = new global::System.Type[length];
				int[] rates = new int[( methods as global::System.Array ).Length];
				#line 440 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				{
					#line 440 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					int _g1 = 0;
					#line 440 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					int _g = length;
					#line 440 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					while (( _g1 < _g )) {
						#line 440 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						int i = _g1++;
						#line 442 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						oargs[i] = args[i];
						if (( args[i] != null )) {
							#line 444 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							ts[i] = args[i].GetType();
						}
						
					}
					
				}
				
				#line 447 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				int last = 0;
				#line 450 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (( methodLength > 1 )) {
					#line 452 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					{
						#line 452 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						int _g11 = 0;
						#line 452 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						int _g2 = methodLength;
						#line 452 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						while (( _g11 < _g2 )) {
							#line 452 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							int i1 = _g11++;
							#line 454 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							global::System.Reflection.ParameterInfo[] @params = methods[i1].GetParameters();
							if (( ( @params as global::System.Array ).Length != length )) {
								#line 456 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								continue;
							}
							else {
								#line 458 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								bool fits = true;
								#line 458 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								int crate = 0;
								{
									#line 459 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
									int _g3 = 0;
									#line 459 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
									int _g21 = ( @params as global::System.Array ).Length;
									#line 459 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
									while (( _g3 < _g21 )) {
										#line 459 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
										int i2 = _g3++;
										#line 461 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
										global::System.Type param = @params[i2].ParameterType;
										string strParam = global::haxe.lang.Runtime.concat(global::Std.@string(param), "");
										#line 463 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
										if (( param.IsAssignableFrom(((global::System.Type) (ts[i2]) )) || ( ( ts[i2] == null ) &&  ! (param.IsValueType)  ) )) {
											#line 466 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
											continue;
										}
										else if (( strParam.StartsWith("haxe.lang.Null") || ( (( ( oargs[i2] == null ) || ( oargs[i2] is global::System.IConvertible ) )) && (((global::System.Type) (typeof(global::System.IConvertible)) )).IsAssignableFrom(((global::System.Type) (param) )) ) )) {
											#line 470 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
											 ++ crate;
											continue;
										}
										else if ( ! (param.ContainsGenericParameters) ) {
											#line 473 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
											fits = false;
											break;
										}
										
									}
									
								}
								
								#line 478 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								if (fits) {
									#line 480 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
									rates[last] = crate;
									methods[last++] = methods[i1];
								}
								
							}
							
						}
						
					}
					
					#line 486 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					methodLength = last;
				}
				else if (( ( methodLength == 1 ) && ( ( methods[0].GetParameters() as global::System.Array ).Length != length ) )) {
					#line 488 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					methodLength = 0;
				}
				
				#line 496 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (( methodLength == 0 )) {
					#line 497 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					throw global::haxe.lang.HaxeException.wrap(global::haxe.lang.Runtime.concat("Invalid calling parameters for method ", ( methods[0] as global::System.Reflection.MemberInfo ).Name));
				}
				
				#line 499 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				double best = global::System.Double.PositiveInfinity;
				int bestMethod = 0;
				#line 501 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				{
					#line 501 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					int _g12 = 0;
					#line 501 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					int _g4 = methodLength;
					#line 501 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					while (( _g12 < _g4 )) {
						#line 501 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						int i3 = _g12++;
						#line 503 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						if (( rates[i3] < best )) {
							#line 505 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							bestMethod = i3;
							best = ((double) (rates[i3]) );
						}
						
					}
					
				}
				
				#line 510 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				methods[0] = methods[bestMethod];
				global::System.Reflection.ParameterInfo[] params1 = methods[0].GetParameters();
				#line 512 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				{
					#line 512 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					int _g13 = 0;
					#line 512 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					int _g5 = ( params1 as global::System.Array ).Length;
					#line 512 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					while (( _g13 < _g5 )) {
						#line 512 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						int i4 = _g13++;
						#line 514 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						global::System.Type param1 = params1[i4].ParameterType;
						string strParam1 = global::haxe.lang.Runtime.concat(global::Std.@string(param1), "");
						object arg = oargs[i4];
						#line 517 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						if (strParam1.StartsWith("haxe.lang.Null")) {
							#line 519 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							oargs[i4] = global::haxe.lang.Runtime.mkNullable(arg, param1);
						}
						else if ((((global::System.Type) (typeof(global::System.IConvertible)) )).IsAssignableFrom(((global::System.Type) (param1) ))) {
							#line 521 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							if (( arg == null )) {
								#line 522 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								if (param1.IsValueType) {
									#line 523 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
									oargs[i4] = global::System.Activator.CreateInstance(((global::System.Type) (param1) ));
								}
								
							}
							else if ( ! (arg.GetType().IsAssignableFrom(((global::System.Type) (param1) ))) ) {
								#line 525 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
								oargs[i4] = (((global::System.IConvertible) (arg) )).ToType(((global::System.Type) (param1) ), default(global::System.IFormatProvider));
							}
							
						}
						
					}
					
				}
				
				#line 530 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (( methods[0].ContainsGenericParameters && ( methods[0] is global::System.Reflection.MethodInfo ) )) {
					#line 532 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					global::System.Reflection.MethodInfo m = ((global::System.Reflection.MethodInfo) (methods[0]) );
					global::System.Type[] tgs = ( m as global::System.Reflection.MethodBase ).GetGenericArguments();
					#line 534 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					{
						#line 534 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						int _g14 = 0;
						#line 534 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						int _g6 = ( tgs as global::System.Array ).Length;
						#line 534 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						while (( _g14 < _g6 )) {
							#line 534 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							int i5 = _g14++;
							#line 536 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							tgs[i5] = typeof(object);
						}
						
					}
					
					#line 538 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					m = m.MakeGenericMethod(((global::System.Type[]) (tgs) ));
					object retg = ( m as global::System.Reflection.MethodBase ).Invoke(((object) (obj) ), ((object[]) (oargs) ));
					#line 540 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return global::haxe.lang.Runtime.unbox(retg);
				}
				
				#line 543 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				global::System.Reflection.MethodBase m1 = methods[0];
				if (( ( obj == null ) && ( m1 is global::System.Reflection.ConstructorInfo ) )) {
					#line 546 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					object ret = (((global::System.Reflection.ConstructorInfo) (m1) )).Invoke(((object[]) (oargs) ));
					return global::haxe.lang.Runtime.unbox(ret);
				}
				
				#line 550 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				object ret1 = m1.Invoke(((object) (obj) ), ((object[]) (oargs) ));
				return global::haxe.lang.Runtime.unbox(ret1);
			}
			#line default
		}
		
		
		public static object unbox(object dyn) {
			#line 556 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( ( dyn != null ) && (global::haxe.lang.Runtime.concat(global::Std.@string(dyn.GetType()), "")).StartsWith("haxe.lang.Null") )) {
				#line 558 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return ((object) (global::haxe.lang.Runtime.callField(dyn, "toDynamic", 1705629508, null)) );
			}
			else {
				#line 560 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return dyn;
			}
			
		}
		#line default
		
		public static object mkNullable(object obj, global::System.Type nullableType) {
			
		if (nullableType.ContainsGenericParameters)
			return haxe.lang.Null<object>.ofDynamic<object>(obj);
		return nullableType.GetMethod("_ofDynamic").Invoke(null, new object[] { obj });
	
		}
		
		
		public static object slowCallField(object obj, string field, global::Array args) {
			#line 649 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( string.Equals(field, "toString") && (( ( args == null ) || ( ((int) (global::haxe.lang.Runtime.getField_f(args, "length", 520590566, true)) ) == 0 ) )) )) {
				#line 651 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return obj.ToString();
			}
			
			#line 653 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( args == null )) {
				#line 653 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				args = new global::Array<object>(new object[]{});
			}
			
			#line 655 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::System.Reflection.BindingFlags bf = default(global::System.Reflection.BindingFlags);
			global::System.Type t = ((global::System.Type) (( obj as global::System.Type )) );
			#line 657 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( t == null )) {
				#line 659 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				string s = ((string) (( obj as string )) );
				if ( ! (string.Equals(s, null)) ) {
					#line 661 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return global::haxe.lang.StringRefl.handleCallField(s, field, args);
				}
				
				#line 662 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				t = obj.GetType();
				global::System.Reflection.BindingFlags this1 = global::System.Reflection.BindingFlags.Instance;
				global::System.Reflection.BindingFlags this2 = ((global::System.Reflection.BindingFlags) (( ((global::System.Reflection.BindingFlags) (this1) ) | ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Public) ) )) );
				global::System.Reflection.BindingFlags this3 = ((global::System.Reflection.BindingFlags) (( ((global::System.Reflection.BindingFlags) (this2) ) | ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.FlattenHierarchy) ) )) );
				bf = ((global::System.Reflection.BindingFlags) (this3) );
			}
			else {
				#line 665 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (( ( t == ((global::System.Type) (typeof(string)) ) ) && string.Equals(field, "fromCharCode") )) {
					#line 666 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return global::haxe.lang.StringExt.fromCharCode(global::haxe.lang.Runtime.toInt(args[0]));
				}
				
				#line 667 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				obj = null;
				global::System.Reflection.BindingFlags this4 = global::System.Reflection.BindingFlags.Static;
				global::System.Reflection.BindingFlags this5 = ((global::System.Reflection.BindingFlags) (( ((global::System.Reflection.BindingFlags) (this4) ) | ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.Public) ) )) );
				bf = ((global::System.Reflection.BindingFlags) (this5) );
			}
			
			#line 671 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::System.Reflection.MethodBase[] mis = ((global::System.Reflection.MethodBase[]) (t.GetMethods(((global::System.Reflection.BindingFlags) (bf) ))) );
			int last = 0;
			#line 673 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			{
				#line 673 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				int _g1 = 0;
				#line 673 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				int _g = ( mis as global::System.Array ).Length;
				#line 673 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				while (( _g1 < _g )) {
					#line 673 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					int i = _g1++;
					#line 675 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					string name = ( mis[i] as global::System.Reflection.MemberInfo ).Name;
					if (string.Equals(name, field)) {
						#line 677 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						mis[last++] = mis[i];
					}
					
				}
				
			}
			
			#line 680 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( ( last == 0 ) && (( string.Equals(field, "__get") || string.Equals(field, "__set") )) )) {
				#line 682 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (string.Equals(field, "__get")) {
					#line 682 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					field = "get_Item";
				}
				else {
					#line 682 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					field = "set_Item";
				}
				
				#line 683 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				{
					#line 683 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					int _g11 = 0;
					#line 683 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					int _g2 = ( mis as global::System.Array ).Length;
					#line 683 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					while (( _g11 < _g2 )) {
						#line 683 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						int i1 = _g11++;
						#line 685 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						string name1 = ( mis[i1] as global::System.Reflection.MemberInfo ).Name;
						if (string.Equals(name1, field)) {
							#line 688 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
							mis[last++] = mis[i1];
						}
						
					}
					
				}
				
			}
			
			#line 693 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( ( last == 0 ) && t.IsCOMObject )) {
				#line 695 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				object[] oargs = new object[((int) (global::haxe.lang.Runtime.getField_f(args, "length", 520590566, true)) )];
				{
					#line 696 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					int _g12 = 0;
					#line 696 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					int _g3 = ( oargs as global::System.Array ).Length;
					#line 696 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					while (( _g12 < _g3 )) {
						#line 696 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						int i2 = _g12++;
						#line 698 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						oargs[i2] = args[i2];
					}
					
				}
				
				#line 700 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return t.InvokeMember(((string) (field) ), ((global::System.Reflection.BindingFlags) (global::System.Reflection.BindingFlags.InvokeMethod) ), default(global::System.Reflection.Binder), ((object) (obj) ), ((object[]) (oargs) ));
			}
			
			#line 703 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( last == 0 )) {
				#line 705 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				throw global::haxe.lang.HaxeException.wrap(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Method \"", field), "\" not found on type "), global::Std.@string(t)));
			}
			
			#line 708 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			return global::haxe.lang.Runtime.callMethod(obj, mis, last, args);
		}
		#line default
		
		public static object callField(object obj, string field, int fieldHash, global::Array args) {
			#line 713 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::haxe.lang.HxObject hxObj = ((global::haxe.lang.HxObject) (( obj as global::haxe.lang.HxObject )) );
			if (( hxObj != null )) {
				#line 715 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return hxObj.__hx_invokeField(field, ( (( fieldHash == 0 )) ? (global::haxe.lang.FieldLookup.hash(field)) : (fieldHash) ), args);
			}
			
			#line 716 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			return global::haxe.lang.Runtime.slowCallField(obj, field, args);
		}
		#line default
		
		public static object getField(object obj, string field, int fieldHash, bool throwErrors) {
			#line 721 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::haxe.lang.HxObject hxObj = ((global::haxe.lang.HxObject) (( obj as global::haxe.lang.HxObject )) );
			if (( hxObj != null )) {
				#line 723 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return hxObj.__hx_getField(field, ( (( fieldHash == 0 )) ? (global::haxe.lang.FieldLookup.hash(field)) : (fieldHash) ), throwErrors, false, false);
			}
			
			#line 725 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			return global::haxe.lang.Runtime.slowGetField(obj, field, throwErrors);
		}
		#line default
		
		public static double getField_f(object obj, string field, int fieldHash, bool throwErrors) {
			#line 730 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::haxe.lang.HxObject hxObj = ((global::haxe.lang.HxObject) (( obj as global::haxe.lang.HxObject )) );
			if (( hxObj != null )) {
				#line 732 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return hxObj.__hx_getField_f(field, ( (( fieldHash == 0 )) ? (global::haxe.lang.FieldLookup.hash(field)) : (fieldHash) ), throwErrors, false);
			}
			
			#line 734 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			return global::haxe.lang.Runtime.toDouble(global::haxe.lang.Runtime.slowGetField(obj, field, throwErrors));
		}
		#line default
		
		public static object setField(object obj, string field, int fieldHash, object @value) {
			#line 739 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::haxe.lang.HxObject hxObj = ((global::haxe.lang.HxObject) (( obj as global::haxe.lang.HxObject )) );
			if (( hxObj != null )) {
				#line 741 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return hxObj.__hx_setField(field, ( (( fieldHash == 0 )) ? (global::haxe.lang.FieldLookup.hash(field)) : (fieldHash) ), @value, false);
			}
			
			#line 743 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			return global::haxe.lang.Runtime.slowSetField(obj, field, @value);
		}
		#line default
		
		public static double setField_f(object obj, string field, int fieldHash, double @value) {
			#line 748 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			global::haxe.lang.HxObject hxObj = ((global::haxe.lang.HxObject) (( obj as global::haxe.lang.HxObject )) );
			if (( hxObj != null )) {
				#line 750 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return hxObj.__hx_setField_f(field, ( (( fieldHash == 0 )) ? (global::haxe.lang.FieldLookup.hash(field)) : (fieldHash) ), @value, false);
			}
			
			#line 752 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			return global::haxe.lang.Runtime.toDouble(global::haxe.lang.Runtime.slowSetField(obj, field, @value));
		}
		#line default
		
		public static string toString(object obj) {
			#line 757 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( obj == null )) {
				#line 758 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return null;
			}
			
			#line 759 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( obj is bool )) {
				#line 760 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (global::haxe.lang.Runtime.toBool((obj))) {
					#line 761 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return "true";
				}
				else {
					#line 763 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					return "false";
				}
				
			}
			
			#line 765 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			return obj.ToString();
		}
		#line default
		
		public static bool typeEq(global::System.Type t1, global::System.Type t2) {
			#line 773 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( ( t1 == null ) || ( t2 == null ) )) {
				#line 774 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return ( t1 == t2 );
			}
			
			#line 776 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			bool t1i = t1.IsInterface;
			#line 778 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( t1i != t2.IsInterface )) {
				#line 780 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				if (t1i) {
					#line 782 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					global::haxe.lang.GenericInterface g = global::haxe.lang.Runtime.getGenericAttr(t1);
					if (( g != null )) {
						#line 784 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						t1 = g.generic;
					}
					
				}
				else {
					#line 786 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					global::haxe.lang.GenericInterface g1 = global::haxe.lang.Runtime.getGenericAttr(t2);
					if (( g1 != null )) {
						#line 788 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						t2 = g1.generic;
					}
					
				}
				
			}
			
			#line 793 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( ( t1.GetGenericArguments() as global::System.Array ).Length > 0 )) {
				#line 793 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				t1 = t1.GetGenericTypeDefinition();
			}
			
			#line 794 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( ( t2.GetGenericArguments() as global::System.Array ).Length > 0 )) {
				#line 794 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				t2 = t2.GetGenericTypeDefinition();
			}
			
			#line 795 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			return global::System.Object.ReferenceEquals(((object) (t1) ), ((object) (t2) ));
		}
		#line default
		
		public static global::haxe.lang.GenericInterface getGenericAttr(global::System.Type t) {
			#line 802 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			{
				#line 802 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				object[] _this = ( t as global::System.Reflection.MemberInfo ).GetCustomAttributes(((bool) (true) ));
				#line 800 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				uint _g_idx = ((uint) (0) );
				#line 802 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				while (((bool) (( _g_idx < ( _this as global::System.Array ).Length )) )) {
					#line 802 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
					object attr = ((object) (_this[((int) (_g_idx++) )]) );
					if (( attr is global::haxe.lang.GenericInterface )) {
						#line 804 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
						return ((global::haxe.lang.GenericInterface) (attr) );
					}
					
				}
				
			}
			
			#line 805 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			return null;
		}
		#line default
		
		public static To genericCast<To>(object obj) {
			
		if (obj is To)
			return (To) obj;
		else if (obj == null)
			return default(To);
		if (typeof(To) == typeof(double))
			return (To)(object) toDouble(obj);
		else if (typeof(To) == typeof(int))
			return (To)(object) toInt(obj);
		else if (typeof(To) == typeof(float))
			return (To)(object)(float)toDouble(obj);
		else if (typeof(To) == typeof(long))
			return (To)(object)(long)toDouble(obj);
		else
			return (To) obj;
	
		}
		
		
		public static string concat(string s1, string s2) {
			
		return (s1 == null ? "null" : s1) + (s2 == null ? "null" : s2);
	
		}
		
		
		public static bool toBool(object dyn) {
			#line 842 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
			if (( dyn == null )) {
				#line 842 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return false;
			}
			else {
				#line 842 "C:\\HaxeToolkit\\haxe\\std\\cs\\internal\\Runtime.hx"
				return (bool)dyn;
			}
			
		}
		#line default
		
	}
}


